//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AppResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        internal static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falla al invocar servicio asíncrono..
        /// </summary>
        internal static string FailAjaxMethod {
            get {
                return ResourceManager.GetString("FailAjaxMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ser una fecha..
        /// </summary>
        internal static string FieldMustBeDate {
            get {
                return ResourceManager.GetString("FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ser un número..
        /// </summary>
        internal static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b style=&apos;color:red&apos;&gt;{0}&lt;/b&gt;.
        /// </summary>
        internal static string HtmlErrorMessage {
            get {
                return ResourceManager.GetString("HtmlErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuera de rango, debe ser un número positivo.
        /// </summary>
        internal static string InvalidNumerMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("InvalidNumerMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de dato no válido..
        /// </summary>
        internal static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo es obligatorio..
        /// </summary>
        internal static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Error/Index.cshtml.
        /// </summary>
        internal static string UrlViewErrorIndex {
            get {
                return ResourceManager.GetString("UrlViewErrorIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Error/NoAutorizado.cshtml.
        /// </summary>
        internal static string UrlViewNoAutorizado {
            get {
                return ResourceManager.GetString("UrlViewNoAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Error/NoEncontrado.cshtml.
        /// </summary>
        internal static string UrlViewNoEncontrado {
            get {
                return ResourceManager.GetString("UrlViewNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Error/PermisoDenegado.cshtml.
        /// </summary>
        internal static string UrlViewPermisoDenegado {
            get {
                return ResourceManager.GetString("UrlViewPermisoDenegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de validación, corrija los datos y vuelva a intentar..
        /// </summary>
        internal static string ValidationFailMessage {
            get {
                return ResourceManager.GetString("ValidationFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un elemento de la lista.
        /// </summary>
        internal static string ValidationMustSelectOption {
            get {
                return ResourceManager.GetString("ValidationMustSelectOption", resourceCulture);
            }
        }
    }
}
