//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUsers
    {
        public int AppUserId { get; set; }
        public string UserId { get; set; }
        public string RoleId { get; set; }
        public string Estatus { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> Gerencia_id { get; set; }
        public Nullable<int> Zona_id { get; set; }
        public Nullable<int> Subestacion_id { get; set; }
    
        public virtual Gerencia Gerencia { get; set; }
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual Subestacion Subestacion { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Zona Zona { get; set; }
    }
}
