//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        public int id { get; set; }
        public int Prueba_id { get; set; }
        public System.DateTime fecha { get; set; }
        public string nombre_archivo { get; set; }
        public string extension { get; set; }
        public byte[] archivo_soporte { get; set; }
        public string nombre_prueba { get; set; }
    
        public virtual Prueba Prueba { get; set; }
    }
}
