//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondicionVarillaje
    {
        public int id { get; set; }
        public int Inspeccion_visual_id { get; set; }
        public Nullable<bool> alineacion { get; set; }
        public string observaciones_alineacion { get; set; }
        public Nullable<bool> pzas_fracturadas_rotas { get; set; }
        public string observaciones_pzafracrot { get; set; }
        public Nullable<bool> corrosion { get; set; }
        public string observaciones_corrosion { get; set; }
        public string condision_pernos { get; set; }
        public string observaciones_pernos { get; set; }
        public Nullable<bool> lubricacion { get; set; }
        public string observaciones_lubricacion { get; set; }
    
        public virtual Inspeccion_visual Inspeccion_visual { get; set; }
    }
}
