//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondicionGabineteCentralizador
    {
        public int id { get; set; }
        public int Prueba_id { get; set; }
        public string tablillas { get; set; }
        public string observaciones_tablillas { get; set; }
        public string contactores { get; set; }
        public string observaciones_contactores { get; set; }
        public string relevadores { get; set; }
        public string observaciones_relevadores { get; set; }
        public string elementos_ctrl { get; set; }
        public string obs_elementos_ctrl { get; set; }
        public Nullable<bool> humedad { get; set; }
        public string observaciones_humedad { get; set; }
        public Nullable<bool> roturas_internas { get; set; }
        public string observaciones_roturasint { get; set; }
        public Nullable<bool> roturas_externas { get; set; }
        public string observaciones_roturasext { get; set; }
        public Nullable<bool> grietas_sello { get; set; }
        public string observaciones_grietassello { get; set; }
        public Nullable<bool> insectos { get; set; }
        public string observaciones_insectos { get; set; }
        public Nullable<bool> desp_pintura_int { get; set; }
        public string observaciones_pinturaint { get; set; }
        public Nullable<bool> desp_pintura_ext { get; set; }
        public string observaciones_pinturaext { get; set; }
        public Nullable<bool> corrosion_interna { get; set; }
        public string observaciones_corrosionint { get; set; }
        public Nullable<bool> corrosion_externa { get; set; }
        public string observaciones_corrosionext { get; set; }
        public string funciona_resis_calefactora { get; set; }
        public string obs_fun_resis_calef { get; set; }
        public string observaciones { get; set; }
    
        public virtual Prueba Prueba { get; set; }
    }
}
