//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondicionGabineteControl
    {
        public int id { get; set; }
        public int Inspeccion_visual_id { get; set; }
        public Nullable<bool> humedad { get; set; }
        public string observaciones_humedad { get; set; }
        public Nullable<bool> roturas { get; set; }
        public string observaciones_roturas { get; set; }
        public Nullable<bool> grietas_sello { get; set; }
        public string observaciones_grietas { get; set; }
        public Nullable<bool> insectos { get; set; }
        public string observaciones_insectos { get; set; }
        public Nullable<bool> desprendimiento_pintura { get; set; }
        public string observaciones_pintura { get; set; }
        public Nullable<bool> corrosion_interna { get; set; }
        public string observaciones_corrosioninterna { get; set; }
        public Nullable<bool> corrosion_externa { get; set; }
        public string observaciones_corrosionexterna { get; set; }
        public string resistencia_calefactora { get; set; }
        public string observaciones_rcalecfactora { get; set; }
        public Nullable<bool> corrosion_conex_tierra { get; set; }
        public string observaciones_corrconx_tierra { get; set; }
        public Nullable<bool> disparo1 { get; set; }
        public string observaciones_disparo1 { get; set; }
        public Nullable<bool> disparo2 { get; set; }
        public string observaciones_disparo2 { get; set; }
        public Nullable<bool> cierre { get; set; }
        public string observaciones_cierre { get; set; }
    
        public virtual Inspeccion_visual Inspeccion_visual { get; set; }
    }
}
