//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.Prueba = new HashSet<Prueba>();
        }
    
        public int id { get; set; }
        public int Gerencia_id { get; set; }
        public int Zona_id { get; set; }
        public int Subestacion_id { get; set; }
        public int Mecanismo_id { get; set; }
        public int AplicacionInterruptor_id { get; set; }
        public int Marca_id { get; set; }
        public int Modelo_id { get; set; }
        public string bahia { get; set; }
        public string ns { get; set; }
        public Nullable<int> anio_fabricacion { get; set; }
        public Nullable<decimal> tension_nominal { get; set; }
        public Nullable<decimal> corriente_nominal { get; set; }
        public Nullable<decimal> corriente_cc { get; set; }
        public Nullable<decimal> bil { get; set; }
        public string disponibilidad_refaccion_st { get; set; }
        public Nullable<decimal> presionSF6 { get; set; }
        public string tipo_unidades_presion { get; set; }
        public Nullable<decimal> presion_alarma { get; set; }
        public string tipo_unidades_presion_alarma { get; set; }
        public Nullable<int> altitud_operacion { get; set; }
        public Nullable<int> altitud_instalacion { get; set; }
        public string dis_estructural { get; set; }
        public string conf_camaras { get; set; }
        public Nullable<decimal> res_estatica_contactos { get; set; }
        public string interruptor_contiene { get; set; }
        public Nullable<decimal> interruptor_resistencia { get; set; }
        public Nullable<decimal> interruptor_capacitor { get; set; }
        public Nullable<System.DateTime> fecha_puestaservicio { get; set; }
        public Nullable<System.DateTime> fultimo_mantenimiento { get; set; }
        public string nivel_contaminacion { get; set; }
        public string tipo_disparo { get; set; }
        public string comando_cierre { get; set; }
        public Nullable<int> distancia_fuga { get; set; }
        public string clase_interruptor { get; set; }
        public string Id_EquipoSAP { get; set; }
        public string UbicaTecnica { get; set; }
        public Nullable<int> voltajeNominalBobina { get; set; }
        public Nullable<int> voltajeNominalBobinaCierre { get; set; }
        public string instrumento_medicionSF6 { get; set; }
        public Nullable<bool> existe_gabinete_centralizador { get; set; }
        public Nullable<bool> existe_gabinetectrl_xfase { get; set; }
    
        public virtual AplicacionInterruptor AplicacionInterruptor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prueba> Prueba { get; set; }
        public virtual Mecanismo Mecanismo { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Subestacion Subestacion { get; set; }
    }
}
