//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccion_visual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspeccion_visual()
        {
            this.CondicionAislador = new HashSet<CondicionAislador>();
            this.CondicionGabineteControl = new HashSet<CondicionGabineteControl>();
            this.CondicionOtrosComponentes = new HashSet<CondicionOtrosComponentes>();
            this.CondicionVarillaje = new HashSet<CondicionVarillaje>();
            this.Densimetro = new HashSet<Densimetro>();
            this.MecanismoHidraulico = new HashSet<MecanismoHidraulico>();
            this.MecanismoNeumatico = new HashSet<MecanismoNeumatico>();
            this.MecanismoResortes = new HashSet<MecanismoResortes>();
            this.Presostato = new HashSet<Presostato>();
        }
    
        public int id { get; set; }
        public int Prueba_id { get; set; }
        public string fase { get; set; }
        public Nullable<int> num_operaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicionAislador> CondicionAislador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicionGabineteControl> CondicionGabineteControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicionOtrosComponentes> CondicionOtrosComponentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicionVarillaje> CondicionVarillaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Densimetro> Densimetro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MecanismoHidraulico> MecanismoHidraulico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MecanismoNeumatico> MecanismoNeumatico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MecanismoResortes> MecanismoResortes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presostato> Presostato { get; set; }
        public virtual Prueba Prueba { get; set; }
    }
}
