//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MecanismoResortes
    {
        public int id { get; set; }
        public int Inspeccion_visual_id { get; set; }
        public string alineacion_resortes { get; set; }
        public string observaciones_alin_resortes { get; set; }
        public string amortiguadores { get; set; }
        public string observaciones_amortiguadores { get; set; }
        public Nullable<bool> corros_desp_pintura { get; set; }
        public string observaciones_cordesp_pintura { get; set; }
        public string motor { get; set; }
        public string observaciones_motor { get; set; }
    
        public virtual Inspeccion_visual Inspeccion_visual { get; set; }
    }
}
