//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MecanismoHidraulico
    {
        public int id { get; set; }
        public int Inspeccion_visual_id { get; set; }
        public string fuga_aceite { get; set; }
        public string observaciones_fugaa { get; set; }
        public string acumulador { get; set; }
        public string observaciones_acumulador { get; set; }
        public string presion_aceite { get; set; }
        public string observaciones_presiona { get; set; }
        public string unidad_control { get; set; }
        public string observaciones_uctrl { get; set; }
        public string valvulas { get; set; }
        public string observaciones_valvulas { get; set; }
        public string burbujas_reservorio { get; set; }
        public string observaciones_burbujasr { get; set; }
        public string compresor { get; set; }
        public string observaciones_compresor { get; set; }
        public string nivel_glicerina { get; set; }
        public string observaciones_nglicerina { get; set; }
    
        public virtual Inspeccion_visual Inspeccion_visual { get; set; }
    }
}
