//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MecanismoNeumatico
    {
        public int id { get; set; }
        public int Inspeccion_visual_id { get; set; }
        public string presion_aire { get; set; }
        public string observaciones_presionaire { get; set; }
        public string fuga_aire { get; set; }
        public string observaciones_fugaaire { get; set; }
        public string valvulas { get; set; }
        public string observaciones_valvulas { get; set; }
        public string corrosion_mecanismo { get; set; }
        public string observaciones_corrmecan { get; set; }
    
        public virtual Inspeccion_visual Inspeccion_visual { get; set; }
    }
}
