//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ModeloSievis : DbContext
    {
        public ModeloSievis()
            : base("name=ModeloSievis")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AplicacionInterruptor> AplicacionInterruptor { get; set; }
        public virtual DbSet<AppParameters> AppParameters { get; set; }
        public virtual DbSet<AppUsers> AppUsers { get; set; }
        public virtual DbSet<Archivo> Archivo { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Catalogo> Catalogo { get; set; }
        public virtual DbSet<CondicionAislador> CondicionAislador { get; set; }
        public virtual DbSet<CondicionGabineteCentralizador> CondicionGabineteCentralizador { get; set; }
        public virtual DbSet<CondicionGabineteControl> CondicionGabineteControl { get; set; }
        public virtual DbSet<CondicionOtrosComponentes> CondicionOtrosComponentes { get; set; }
        public virtual DbSet<CondicionVarillaje> CondicionVarillaje { get; set; }
        public virtual DbSet<Densimetro> Densimetro { get; set; }
        public virtual DbSet<DetalleCatalogo> DetalleCatalogo { get; set; }
        public virtual DbSet<Equipo> Equipo { get; set; }
        public virtual DbSet<Eventos> Eventos { get; set; }
        public virtual DbSet<Gerencia> Gerencia { get; set; }
        public virtual DbSet<indiceSaludPrueba> indiceSaludPrueba { get; set; }
        public virtual DbSet<Inspeccion_visual> Inspeccion_visual { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Mecanismo> Mecanismo { get; set; }
        public virtual DbSet<MecanismoHidraulico> MecanismoHidraulico { get; set; }
        public virtual DbSet<MecanismoNeumatico> MecanismoNeumatico { get; set; }
        public virtual DbSet<MecanismoResortes> MecanismoResortes { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<ParametroCondicion> ParametroCondicion { get; set; }
        public virtual DbSet<ParametrosFabricantePE> ParametrosFabricantePE { get; set; }
        public virtual DbSet<ParametrosFabricantePR> ParametrosFabricantePR { get; set; }
        public virtual DbSet<Presostato> Presostato { get; set; }
        public virtual DbSet<Prueba> Prueba { get; set; }
        public virtual DbSet<PruebaEspecial> PruebaEspecial { get; set; }
        public virtual DbSet<PruebaEspecialDetalle> PruebaEspecialDetalle { get; set; }
        public virtual DbSet<PruebaRutina> PruebaRutina { get; set; }
        public virtual DbSet<PruebaRutinaDetalle> PruebaRutinaDetalle { get; set; }
        public virtual DbSet<Rangos> Rangos { get; set; }
        public virtual DbSet<Subestacion> Subestacion { get; set; }
        public virtual DbSet<Variables> Variables { get; set; }
        public virtual DbSet<Zona> Zona { get; set; }
        public virtual DbSet<ParametrosFabricantePE_OLD> ParametrosFabricantePE_OLD { get; set; }
        public virtual DbSet<vCatalogoPuntuaciones> vCatalogoPuntuaciones { get; set; }
        public virtual DbSet<vCatParamVarRango> vCatParamVarRango { get; set; }
        public virtual DbSet<vDatosEquipo> vDatosEquipo { get; set; }
        public virtual DbSet<vDatosPrueba> vDatosPrueba { get; set; }
        public virtual DbSet<vdPrConfInterruptor> vdPrConfInterruptor { get; set; }
        public virtual DbSet<vdPrMecOperacion> vdPrMecOperacion { get; set; }
        public virtual DbSet<vdPrSecVerifProtecciones> vdPrSecVerifProtecciones { get; set; }
        public virtual DbSet<vdPrUnidadRuptora> vdPrUnidadRuptora { get; set; }
        public virtual DbSet<vIVcondAislador> vIVcondAislador { get; set; }
        public virtual DbSet<vIVcondDensimetro> vIVcondDensimetro { get; set; }
        public virtual DbSet<vIVcondGabCentralizador> vIVcondGabCentralizador { get; set; }
        public virtual DbSet<vIVcondGabControl> vIVcondGabControl { get; set; }
        public virtual DbSet<vIVcondGabControlMonitoreo> vIVcondGabControlMonitoreo { get; set; }
        public virtual DbSet<vIVcondOtrosComp> vIVcondOtrosComp { get; set; }
        public virtual DbSet<vIVcondPresostato> vIVcondPresostato { get; set; }
        public virtual DbSet<vIVcondVarillaje> vIVcondVarillaje { get; set; }
        public virtual DbSet<vIVCPCms> vIVCPCms { get; set; }
        public virtual DbSet<vIVIndiceSalud> vIVIndiceSalud { get; set; }
        public virtual DbSet<vIVmecHidraulico> vIVmecHidraulico { get; set; }
        public virtual DbSet<vIVmecNeumatico> vIVmecNeumatico { get; set; }
        public virtual DbSet<vIVmecResortes> vIVmecResortes { get; set; }
        public virtual DbSet<vParametrosVariablesPeso> vParametrosVariablesPeso { get; set; }
        public virtual DbSet<vPeCondAislamientoUR> vPeCondAislamientoUR { get; set; }
        public virtual DbSet<vPeMecanismoOperacion> vPeMecanismoOperacion { get; set; }
        public virtual DbSet<vPruebasEquipoIndice> vPruebasEquipoIndice { get; set; }
        public virtual DbSet<vPuntuacionCondAislador> vPuntuacionCondAislador { get; set; }
        public virtual DbSet<vPuntuacionDensimetro> vPuntuacionDensimetro { get; set; }
        public virtual DbSet<vPuntuacionGabCentralizador> vPuntuacionGabCentralizador { get; set; }
        public virtual DbSet<vPuntuacionGabControl> vPuntuacionGabControl { get; set; }
        public virtual DbSet<vPuntuacionGabCtrlMonitoreo> vPuntuacionGabCtrlMonitoreo { get; set; }
        public virtual DbSet<vPuntuacionMHidraulico> vPuntuacionMHidraulico { get; set; }
        public virtual DbSet<vPuntuacionMNeumatico> vPuntuacionMNeumatico { get; set; }
        public virtual DbSet<vPuntuacionMResortes> vPuntuacionMResortes { get; set; }
        public virtual DbSet<vPuntuacionOtrosComp> vPuntuacionOtrosComp { get; set; }
        public virtual DbSet<vPuntuacionPresostato> vPuntuacionPresostato { get; set; }
        public virtual DbSet<vPuntuacionVarillaje> vPuntuacionVarillaje { get; set; }
    
        public virtual int EliminarEquipo(Nullable<int> equipo_id)
        {
            var equipo_idParameter = equipo_id.HasValue ?
                new ObjectParameter("equipo_id", equipo_id) :
                new ObjectParameter("equipo_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarEquipo", equipo_idParameter);
        }
    
        public virtual int EliminarPrueba(Nullable<int> prueba_id)
        {
            var prueba_idParameter = prueba_id.HasValue ?
                new ObjectParameter("prueba_id", prueba_id) :
                new ObjectParameter("prueba_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarPrueba", prueba_idParameter);
        }
    }
}
