//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosFabricantePE_OLD
    {
        public int id { get; set; }
        public int Marca_id { get; set; }
        public int Modelo_id { get; set; }
        public Nullable<decimal> tiempoCargaResorte { get; set; }
        public Nullable<decimal> anguloGiro { get; set; }
        public Nullable<decimal> factorConversion { get; set; }
        public Nullable<decimal> carreraTotal { get; set; }
        public Nullable<decimal> velocidadInferiorA { get; set; }
        public Nullable<decimal> velocidadSuperiorA { get; set; }
        public Nullable<decimal> carreraTotalIncremento { get; set; }
        public Nullable<decimal> sobreviajeA { get; set; }
        public string criterioSobreviaje { get; set; }
        public Nullable<decimal> reboteA { get; set; }
        public Nullable<decimal> velocidadInferiorC { get; set; }
        public Nullable<decimal> velocidadSuperiorC { get; set; }
        public Nullable<decimal> sobreviajeC { get; set; }
        public Nullable<decimal> reboteC { get; set; }
        public Nullable<decimal> penetracionC { get; set; }
        public Nullable<decimal> bobinaAperturaCorrientePico { get; set; }
        public Nullable<decimal> bobinaCierreCorrientePico { get; set; }
        public decimal ParametrosFabricantePE_ID { get; set; }
    }
}
