//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosFabricantePE
    {
        public int id { get; set; }
        public int MarcaId { get; set; }
        public int ModeloId { get; set; }
        public Nullable<decimal> toTAperturaD1LimInf { get; set; }
        public Nullable<decimal> toTAperturaD1LimSup { get; set; }
        public Nullable<decimal> toTAperturaD2LimInf { get; set; }
        public Nullable<decimal> toTAperturaD2LimSup { get; set; }
        public Nullable<decimal> toTCierreLimInf { get; set; }
        public Nullable<decimal> toTCierreLimSup { get; set; }
        public Nullable<decimal> toTCierreApeCALimInf { get; set; }
        public Nullable<decimal> toTCierreApeCALimSup { get; set; }
        public Nullable<decimal> toTEntResPreLimInf { get; set; }
        public Nullable<decimal> toTEntResPreLimSup { get; set; }
        public Nullable<decimal> pdCarrTotalLimInf { get; set; }
        public Nullable<decimal> pdCarrTotalLimSup { get; set; }
        public Nullable<decimal> pdAnguloGiro { get; set; }
        public Nullable<decimal> pdFactoConversion { get; set; }
        public Nullable<decimal> daVelocidadLimInf { get; set; }
        public Nullable<decimal> daVelocidadLimSup { get; set; }
        public Nullable<decimal> daSobreviaje { get; set; }
        public Nullable<decimal> daRebote { get; set; }
        public Nullable<decimal> dcVelocidadLimInf { get; set; }
        public Nullable<decimal> dcVelocidadLimSup { get; set; }
        public Nullable<decimal> dcSobreviaje { get; set; }
        public Nullable<decimal> dcRebote { get; set; }
        public Nullable<decimal> dcPenetracionLimInf { get; set; }
        public Nullable<decimal> dcPenetracionLimSup { get; set; }
        public Nullable<decimal> boTensionNominal { get; set; }
        public Nullable<decimal> boAperturaIPico { get; set; }
        public Nullable<decimal> boCierreIPico { get; set; }
        public Nullable<decimal> mtrTensionNominal { get; set; }
        public Nullable<decimal> mtrCorrienteArranque { get; set; }
        public Nullable<decimal> mtrTCargaResorteLimInf { get; set; }
        public Nullable<decimal> mtrTCargaResorteLimSup { get; set; }
    
        public virtual Modelo Modelo { get; set; }
    }
}
