//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruebaRutinaDetalle
    {
        public int id { get; set; }
        public int PruebaRutina_id { get; set; }
        public string fase { get; set; }
        public string unidad_medicion_humedad { get; set; }
        public Nullable<decimal> humedad { get; set; }
        public Nullable<decimal> purezasf6 { get; set; }
        public Nullable<decimal> aire { get; set; }
        public string unidad_medicion_presion { get; set; }
        public Nullable<decimal> presion { get; set; }
        public Nullable<decimal> tapertura_d1c1 { get; set; }
        public Nullable<decimal> tapertura_d1c2 { get; set; }
        public Nullable<decimal> tapertura_d2c1 { get; set; }
        public Nullable<decimal> tapertura_d2c2 { get; set; }
        public Nullable<decimal> tcierre_c1 { get; set; }
        public Nullable<decimal> tcierre_c2 { get; set; }
        public Nullable<decimal> tent_resprein_c1 { get; set; }
        public Nullable<decimal> tent_resprein_c2 { get; set; }
        public Nullable<decimal> tcierreapertura_c1 { get; set; }
        public Nullable<decimal> tcierreapertura_c2 { get; set; }
        public Nullable<decimal> res_estat_contactos_d1c1 { get; set; }
        public Nullable<decimal> res_estat_contactos_d1c2 { get; set; }
        public Nullable<decimal> resitencia_ohmica_rpi_c1 { get; set; }
        public Nullable<decimal> capacitancia_condesadores_c1 { get; set; }
        public Nullable<decimal> resitencia_ohmica_rpi_c2 { get; set; }
        public Nullable<decimal> capacitancia_condesadores_c2 { get; set; }
    
        public virtual PruebaRutina PruebaRutina { get; set; }
    }
}
