//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prueba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prueba()
        {
            this.Archivo = new HashSet<Archivo>();
            this.CondicionGabineteCentralizador = new HashSet<CondicionGabineteCentralizador>();
            this.Inspeccion_visual = new HashSet<Inspeccion_visual>();
            this.PruebaEspecial = new HashSet<PruebaEspecial>();
            this.PruebaRutina = new HashSet<PruebaRutina>();
        }
    
        public int id { get; set; }
        public int Equipo_id { get; set; }
        public System.DateTime fecha_prueba { get; set; }
        public Nullable<System.DateTime> fecha_inspeccion { get; set; }
        public string instrumento_medicionSF6 { get; set; }
        public Nullable<bool> existe_gabinete_centralizador { get; set; }
        public Nullable<bool> existe_gabinetectrl_xfase { get; set; }
        public bool evalBasica { get; set; }
        public bool evalExtendida { get; set; }
        public Nullable<decimal> indiceSaludBasica { get; set; }
        public Nullable<decimal> indiceSaludExtendida { get; set; }
        public Nullable<decimal> indiceConfiabilidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archivo> Archivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CondicionGabineteCentralizador> CondicionGabineteCentralizador { get; set; }
        public virtual Equipo Equipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspeccion_visual> Inspeccion_visual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PruebaEspecial> PruebaEspecial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PruebaRutina> PruebaRutina { get; set; }
    }
}
