//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruebaRutina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PruebaRutina()
        {
            this.PruebaRutinaDetalle = new HashSet<PruebaRutinaDetalle>();
        }
    
        public int id { get; set; }
        public int Prueba_id { get; set; }
        public string seccuencia_displibre { get; set; }
        public string pba_antibombeo { get; set; }
        public string discrepancia_polos { get; set; }
        public Nullable<decimal> ttotal_discrepancia { get; set; }
        public Nullable<bool> fuga { get; set; }
        public Nullable<int> frecuencia_llenado_SF6 { get; set; }
        public Nullable<bool> muestreo_gas_xfase { get; set; }
    
        public virtual Prueba Prueba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PruebaRutinaDetalle> PruebaRutinaDetalle { get; set; }
    }
}
