//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruebaEspecialDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PruebaEspecialDetalle()
        {
            this.Eventos = new HashSet<Eventos>();
        }
    
        public int id { get; set; }
        public int PruebaEspecial_id { get; set; }
        public string fase { get; set; }
        public Nullable<decimal> long_contac_arqueo_c1 { get; set; }
        public Nullable<decimal> long_contac_arqueo_c2 { get; set; }
        public Nullable<decimal> temMaxTermSuperior_c1 { get; set; }
        public Nullable<decimal> temMaxTermSuperior_c2 { get; set; }
        public Nullable<decimal> temMaxTermInferior_c1 { get; set; }
        public Nullable<decimal> temMaxTermInferior_c2 { get; set; }
        public string ubicacion_tempmax { get; set; }
        public Nullable<decimal> ipd1 { get; set; }
        public Nullable<decimal> t1d1 { get; set; }
        public Nullable<decimal> t2d1 { get; set; }
        public Nullable<decimal> ttd1 { get; set; }
        public Nullable<decimal> ipd2 { get; set; }
        public Nullable<decimal> t1d2 { get; set; }
        public Nullable<decimal> t2d2 { get; set; }
        public Nullable<decimal> ttd2 { get; set; }
        public Nullable<decimal> ip_cierre { get; set; }
        public Nullable<decimal> t1_cierre { get; set; }
        public Nullable<decimal> t2_cierre { get; set; }
        public Nullable<decimal> tt_cierre { get; set; }
        public Nullable<decimal> pda_velocidad_ap1 { get; set; }
        public Nullable<decimal> pda_carreratot_ap1 { get; set; }
        public Nullable<decimal> pda_sobrerecorrido_ap1 { get; set; }
        public Nullable<decimal> pda_rebote_ap1 { get; set; }
        public Nullable<decimal> pda_velocidad_ap2 { get; set; }
        public Nullable<decimal> pda_carreratot_ap2 { get; set; }
        public Nullable<decimal> pda_sobrerecorrido_ap2 { get; set; }
        public Nullable<decimal> pda_rebote_ap2 { get; set; }
        public Nullable<decimal> pardescierre_velocidad { get; set; }
        public Nullable<decimal> pardescierre_carreratot { get; set; }
        public Nullable<decimal> pardescierre_sobrerecorrido { get; set; }
        public Nullable<decimal> pardescierre_rebote { get; set; }
        public Nullable<decimal> pardescierre_penetracion { get; set; }
        public Nullable<decimal> pardescierre_penetracion_c2 { get; set; }
        public Nullable<decimal> subprodsf6_so2 { get; set; }
        public Nullable<decimal> subprodsf6_hf { get; set; }
        public Nullable<decimal> subprodsf6_cf4 { get; set; }
        public Nullable<decimal> tapertura_c1 { get; set; }
        public Nullable<decimal> tapertura_c2 { get; set; }
        public Nullable<decimal> tapertura_cierre_c1 { get; set; }
        public Nullable<decimal> tapertura_cierre_c2 { get; set; }
        public Nullable<decimal> tcierre_apertura1_c1 { get; set; }
        public Nullable<decimal> tcierre_apertura1_c2 { get; set; }
        public Nullable<decimal> tcierre_apertura2_c1 { get; set; }
        public Nullable<decimal> tcierre_apertura2_c2 { get; set; }
        public Nullable<decimal> imotor { get; set; }
        public Nullable<decimal> tcarga_resorte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eventos> Eventos { get; set; }
        public virtual PruebaEspecial PruebaEspecial { get; set; }
    }
}
