//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rangos
    {
        public int id { get; set; }
        public int Variable_id { get; set; }
        public string nomRango { get; set; }
        public Nullable<decimal> valorMenor { get; set; }
        public Nullable<decimal> valorMayor { get; set; }
        public string observacion { get; set; }
        public string recomendacion { get; set; }
    
        public virtual Variables Variables { get; set; }
    }
}
