//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Variables()
        {
            this.Rangos = new HashSet<Rangos>();
        }
    
        public int id { get; set; }
        public int ParametroCondicion_id { get; set; }
        public string nomVariable { get; set; }
        public Nullable<decimal> peso { get; set; }
    
        public virtual ParametroCondicion ParametroCondicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rangos> Rangos { get; set; }
    }
}
