//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCatParamVarRango
    {
        public int catalogoId { get; set; }
        public int parametroId { get; set; }
        public int variableId { get; set; }
        public int rangoId { get; set; }
        public string catalogo { get; set; }
        public string parametro { get; set; }
        public decimal parPeso { get; set; }
        public string variable { get; set; }
        public Nullable<decimal> varPeso { get; set; }
        public string rango { get; set; }
        public Nullable<decimal> valorMenor { get; set; }
        public Nullable<decimal> valorMayor { get; set; }
        public string observacion { get; set; }
        public string recomendacion { get; set; }
    }
}
