//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDatosEquipo
    {
        public int id { get; set; }
        public string gerencia { get; set; }
        public string zona { get; set; }
        public string subestacion { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string mecanismo { get; set; }
        public string aplicacion { get; set; }
        public Nullable<int> afabricacion { get; set; }
        public Nullable<System.DateTime> fecha_puestaservicio { get; set; }
        public string bahia { get; set; }
        public string ns { get; set; }
        public Nullable<decimal> tension_nominal { get; set; }
        public Nullable<decimal> corriente_nominal { get; set; }
        public string disestructural { get; set; }
        public string configuracioncamaras { get; set; }
        public int Zona_id { get; set; }
        public int Gerencia_id { get; set; }
        public string Id_EquipoSAP { get; set; }
    }
}
