//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vdPrUnidadRuptora
    {
        public int pruebaId { get; set; }
        public string fase { get; set; }
        public Nullable<decimal> res_estat_contactos_d1c1 { get; set; }
        public Nullable<decimal> res_estat_contactos_d1c2 { get; set; }
        public Nullable<decimal> resitencia_ohmica_rpi_c1 { get; set; }
        public Nullable<decimal> resitencia_ohmica_rpi_c2 { get; set; }
        public Nullable<decimal> capacitancia_condesadores_c1 { get; set; }
        public Nullable<decimal> capacitancia_condesadores_c2 { get; set; }
        public Nullable<decimal> humedad { get; set; }
        public string unidad_medicion_humedad { get; set; }
        public Nullable<decimal> purezasf6 { get; set; }
        public Nullable<decimal> aire { get; set; }
        public Nullable<int> frecuencia_llenado_sf6 { get; set; }
        public decimal presionSF6 { get; set; }
        public string unidadPresionSF6 { get; set; }
        public Nullable<decimal> presion_alarma { get; set; }
        public Nullable<decimal> presionsf6_fase { get; set; }
        public string unidadPresionSF6Fase { get; set; }
    }
}
