//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vdPrSecVerifProtecciones
    {
        public int Prueba_id { get; set; }
        public string fase { get; set; }
        public string seccuencia_displibre { get; set; }
        public Nullable<decimal> tcierreapertura_c1 { get; set; }
        public Nullable<decimal> tcierreapertura_c2 { get; set; }
        public string pba_antibombeo { get; set; }
        public string discrepancia_polos { get; set; }
        public Nullable<decimal> ttotal_discrepancia { get; set; }
    }
}
