//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vIVCPCms
    {
        public int pruebaId { get; set; }
        public int catId { get; set; }
        public int paramId { get; set; }
        public int varId { get; set; }
        public string catalogo { get; set; }
        public string parametro { get; set; }
        public string nomVariable { get; set; }
        public Nullable<decimal> varPeso { get; set; }
        public Nullable<decimal> CPCm { get; set; }
    }
}
