//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPeCondAislamientoUR
    {
        public int Prueba_id { get; set; }
        public int Id { get; set; }
        public string fase { get; set; }
        public Nullable<decimal> long_contac_arqueo_c1 { get; set; }
        public Nullable<decimal> long_contac_arqueo_c2 { get; set; }
        public Nullable<decimal> temMaxTermInferior_c1 { get; set; }
        public Nullable<decimal> temMaxTermInferior_c2 { get; set; }
        public Nullable<decimal> temMaxTermSuperior_c1 { get; set; }
        public Nullable<decimal> temMaxTermSuperior_c2 { get; set; }
        public string ubicacion_tempmax { get; set; }
        public Nullable<decimal> subprodsf6_so2 { get; set; }
        public Nullable<decimal> subprodsf6_hf { get; set; }
        public Nullable<decimal> subprodsf6_cf4 { get; set; }
    }
}
