//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPeMecanismoOperacion
    {
        public int Prueba_id { get; set; }
        public int pruebaEspecialId { get; set; }
        public int peDetalleId { get; set; }
        public string fase { get; set; }
        public string func_bobina_aper70d1 { get; set; }
        public string func_bobina_aper70d2 { get; set; }
        public string func_bobina_cierre85 { get; set; }
        public Nullable<decimal> arranque_minbobd1 { get; set; }
        public Nullable<decimal> arranque_minbobd2 { get; set; }
        public Nullable<decimal> arranque_minbob_cierre { get; set; }
        public Nullable<decimal> ipd1 { get; set; }
        public Nullable<decimal> t1d1 { get; set; }
        public Nullable<decimal> t2d1 { get; set; }
        public Nullable<decimal> ttd1 { get; set; }
        public Nullable<decimal> ipd2 { get; set; }
        public Nullable<decimal> t1d2 { get; set; }
        public Nullable<decimal> t2d2 { get; set; }
        public Nullable<decimal> ttd2 { get; set; }
        public Nullable<decimal> ip_cierre { get; set; }
        public Nullable<decimal> t1_cierre { get; set; }
        public Nullable<decimal> t2_cierre { get; set; }
        public Nullable<decimal> tt_cierre { get; set; }
        public Nullable<decimal> pda_velocidad_ap1 { get; set; }
        public Nullable<decimal> pda_carreratot_ap1 { get; set; }
        public Nullable<decimal> pda_sobrerecorrido_ap1 { get; set; }
        public Nullable<decimal> pda_rebote_ap1 { get; set; }
        public Nullable<decimal> pda_velocidad_ap2 { get; set; }
        public Nullable<decimal> pda_carreratot_ap2 { get; set; }
        public Nullable<decimal> pda_sobrerecorrido_ap2 { get; set; }
        public Nullable<decimal> pda_rebote_ap2 { get; set; }
        public Nullable<decimal> pardescierre_velocidad { get; set; }
        public Nullable<decimal> pardescierre_carreratot { get; set; }
        public Nullable<decimal> pardescierre_sobrerecorrido { get; set; }
        public Nullable<decimal> pardescierre_rebote { get; set; }
        public Nullable<decimal> pardescierre_penetracion { get; set; }
        public Nullable<decimal> pardescierre_penetracion_c2 { get; set; }
        public string sec_nominal_operacion { get; set; }
        public Nullable<decimal> tapertura_c1 { get; set; }
        public Nullable<decimal> tapertura_c2 { get; set; }
        public Nullable<decimal> tapertura_cierre_c1 { get; set; }
        public Nullable<decimal> tapertura_cierre_c2 { get; set; }
        public Nullable<decimal> tcierre_apertura1_c1 { get; set; }
        public Nullable<decimal> tcierre_apertura1_c2 { get; set; }
        public Nullable<decimal> tcierre_apertura2_c1 { get; set; }
        public Nullable<decimal> tcierre_apertura2_c2 { get; set; }
        public Nullable<decimal> imotor { get; set; }
        public Nullable<decimal> tcarga_resorte { get; set; }
        public Nullable<short> numero_motores { get; set; }
    }
}
