//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sievis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPruebasEquipoIndice
    {
        public int equipoId { get; set; }
        public int pruebaid { get; set; }
        public string gerencia { get; set; }
        public string zona { get; set; }
        public string subestacion { get; set; }
        public string bahia { get; set; }
        public string ns { get; set; }
        public Nullable<decimal> tension_nominal { get; set; }
        public string dis_estructural { get; set; }
        public string instrumento_medicionSF6 { get; set; }
        public Nullable<bool> existe_gabinete_centralizador { get; set; }
        public Nullable<bool> existe_gabinetectrl_xfase { get; set; }
        public string disEstructural { get; set; }
        public string confCamaras { get; set; }
        public Nullable<System.DateTime> fecha_inspeccion { get; set; }
        public string insMedicionSF6 { get; set; }
        public string GabCentralizador { get; set; }
        public string GabCtrlFase { get; set; }
        public string evaluacionBasica { get; set; }
        public string evaluacionExtendida { get; set; }
        public bool evalBasica { get; set; }
        public Nullable<decimal> indiceSaludBasica { get; set; }
        public bool evalExtendida { get; set; }
        public Nullable<decimal> indiceSaludExtendida { get; set; }
        public Nullable<decimal> indiceConfiabilidad { get; set; }
        public int Gerencia_id { get; set; }
        public int Zona_id { get; set; }
        public int Subestacion_id { get; set; }
        public System.DateTime fecha_prueba { get; set; }
    }
}
